VouchOwner: '1228243185579589754'

ChannelId: '1228269677462163509'

# time it takes to send vouches
TimeLimit: {
  low: 0 ,
  high: 0
}

formats: ['vouch' , 'rep' , '+vouch' , '+rep']

# total number of vouches
Number: 99
